package com.bluehouseinc.dataconverter.parsers.esp.model.statements;

public enum EspStatementType {
	ABANDON,AFTER, AGENT, APPL, APPLEND, CALENDAR, DATASET, DELAYSUB, LATESUB, DUEOUT, EARLYSUB, ESPNOMSG, ESP, EVENT, JOB, MEMBER,
	OPTIONS, PID, PREREQ, RELEASE, RELDELAY, RESOURCE, RUN, SEND, SETVAR, STARTMODE, SUBAPPL, TAG, USER, TRIGGER_FILE,INVOKE,
}
