//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.09 at 11:04:38 AM EST
//

package com.bluehouseinc.dataconverter.parsers.bmc.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import lombok.ToString;

/**
 * <p>
 * Java class for CaptureData complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CaptureData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="SEARCH_STRING" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SKIP_LINES" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="SKIP_COLUMNS" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="BY_WHAT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DELIMITER" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="COUNT_TO_TAKE" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="VARIABLE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FUTURE_USE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@ToString
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CaptureData")
public class CaptureData {

	@XmlAttribute(name = "SEARCH_STRING")
	protected String searchstring;
	@XmlAttribute(name = "SKIP_LINES")
	protected Integer skiplines;
	@XmlAttribute(name = "SKIP_COLUMNS")
	protected Integer skipcolumns;
	@XmlAttribute(name = "BY_WHAT")
	protected String bywhat;
	@XmlAttribute(name = "DELIMITER")
	protected String delimiter;
	@XmlAttribute(name = "COUNT_TO_TAKE")
	protected Integer counttotake;
	@XmlAttribute(name = "VARIABLE")
	protected String variable;
	@XmlAttribute(name = "FUTURE_USE")
	protected String futureuse;

	/**
	 * Gets the value of the searchstring property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getSEARCHSTRING() {
		return searchstring;
	}

	/**
	 * Sets the value of the searchstring property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setSEARCHSTRING(String value) {
		this.searchstring = value;
	}

	/**
	 * Gets the value of the skiplines property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getSKIPLINES() {
		return skiplines;
	}

	/**
	 * Sets the value of the skiplines property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setSKIPLINES(Integer value) {
		this.skiplines = value;
	}

	/**
	 * Gets the value of the skipcolumns property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getSKIPCOLUMNS() {
		return skipcolumns;
	}

	/**
	 * Sets the value of the skipcolumns property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setSKIPCOLUMNS(Integer value) {
		this.skipcolumns = value;
	}

	/**
	 * Gets the value of the bywhat property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getBYWHAT() {
		return bywhat;
	}

	/**
	 * Sets the value of the bywhat property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setBYWHAT(String value) {
		this.bywhat = value;
	}

	/**
	 * Gets the value of the delimiter property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDELIMITER() {
		return delimiter;
	}

	/**
	 * Sets the value of the delimiter property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDELIMITER(String value) {
		this.delimiter = value;
	}

	/**
	 * Gets the value of the counttotake property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getCOUNTTOTAKE() {
		return counttotake;
	}

	/**
	 * Sets the value of the counttotake property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setCOUNTTOTAKE(Integer value) {
		this.counttotake = value;
	}

	/**
	 * Gets the value of the variable property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getVARIABLE() {
		return variable;
	}

	/**
	 * Sets the value of the variable property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setVARIABLE(String value) {
		this.variable = value;
	}

	/**
	 * Gets the value of the futureuse property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getFUTUREUSE() {
		return futureuse;
	}

	/**
	 * Sets the value of the futureuse property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setFUTUREUSE(String value) {
		this.futureuse = value;
	}

}
