//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.09 at 11:04:38 AM EST
//

package com.bluehouseinc.dataconverter.parsers.bmc.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ClientData complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ClientData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;choice&gt;
 *           &lt;element name="WCM_NOTES_DATA" type="{}WCMNotesData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="INSTRUCTION" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="INSTRUCTION_READ" type="{}emBoolean" /&gt;
 *       &lt;attribute name="COMMENT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="COMMENT_READ" type="{}emBoolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClientData", propOrder = { "wcmnotesdata" })
public class ClientData {

	@XmlElement(name = "WCM_NOTES_DATA")
	protected List<WCMNotesData> wcmnotesdata;
	@XmlAttribute(name = "INSTRUCTION")
	protected String instruction;
	@XmlAttribute(name = "INSTRUCTION_READ")
	protected String instructionread;
	@XmlAttribute(name = "COMMENT")
	protected String comment;
	@XmlAttribute(name = "COMMENT_READ")
	protected String commentread;

	/**
	 * Gets the value of the wcmnotesdata property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the wcmnotesdata property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getWCMNOTESDATA().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link WCMNotesData }
	 *
	 *
	 */
	public List<WCMNotesData> getWCMNOTESDATA() {
		if (wcmnotesdata == null) {
			wcmnotesdata = new ArrayList<>();
		}
		return this.wcmnotesdata;
	}

	/**
	 * Gets the value of the instruction property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getINSTRUCTION() {
		return instruction;
	}

	/**
	 * Sets the value of the instruction property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setINSTRUCTION(String value) {
		this.instruction = value;
	}

	/**
	 * Gets the value of the instructionread property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getINSTRUCTIONREAD() {
		return instructionread;
	}

	/**
	 * Sets the value of the instructionread property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setINSTRUCTIONREAD(String value) {
		this.instructionread = value;
	}

	/**
	 * Gets the value of the comment property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCOMMENT() {
		return comment;
	}

	/**
	 * Sets the value of the comment property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCOMMENT(String value) {
		this.comment = value;
	}

	/**
	 * Gets the value of the commentread property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCOMMENTREAD() {
		return commentread;
	}

	/**
	 * Sets the value of the commentread property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCOMMENTREAD(String value) {
		this.commentread = value;
	}

}
