//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.09 at 11:04:38 AM EST
//

package com.bluehouseinc.dataconverter.parsers.bmc.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import lombok.ToString;

/**
 * <p>
 * Java class for DoCondData complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DoCondData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ODATE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SIGN" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@ToString
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DoCondData")
public class DoCondData {

	@XmlAttribute(name = "NAME")
	protected String name;
	@XmlAttribute(name = "ODATE")
	protected String odate;
	@XmlAttribute(name = "SIGN")
	protected String sign;

	/**
	 * Gets the value of the name property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getNAME() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setNAME(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the odate property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getODATE() {
		return odate;
	}

	/**
	 * Sets the value of the odate property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setODATE(String value) {
		this.odate = value;
	}

	/**
	 * Gets the value of the sign property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getSIGN() {
		return sign;
	}

	/**
	 * Sets the value of the sign property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setSIGN(String value) {
		this.sign = value;
	}

}
