//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.09 at 11:04:38 AM EST
//

package com.bluehouseinc.dataconverter.parsers.bmc.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

import lombok.ToString;

/**
 * <p>
 * Java class for DoForceJobData complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DoForceJobData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;choice&gt;
 *           &lt;element name="AUTOEDIT2" type="{}SetVarData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="AUTOEDIT" type="{}SetVarDataOld" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="VARIABLE" type="{}SetVarData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="TABLE_NAME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DSN" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ODATE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="REMOTE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DATACENTER" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@ToString
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DoForceJobData", propOrder = { "autoedit2OrAUTOEDITOrVARIABLE" })
public class DoForceJobData {

	@XmlElementRefs({ @XmlElementRef(name = "AUTOEDIT2", type = JAXBElement.class, required = false), @XmlElementRef(name = "AUTOEDIT", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "VARIABLE", type = JAXBElement.class, required = false) })
	protected List<JAXBElement<?>> autoedit2OrAUTOEDITOrVARIABLE;
	@XmlAttribute(name = "TABLE_NAME")
	protected String tablename;
	@XmlAttribute(name = "NAME")
	protected String name;
	@XmlAttribute(name = "DSN")
	protected String dsn;
	@XmlAttribute(name = "ODATE")
	protected String odate;
	@XmlAttribute(name = "REMOTE")
	protected String remote;
	@XmlAttribute(name = "DATACENTER")
	protected String datacenter;

	/**
	 * Gets the value of the autoedit2OrAUTOEDITOrVARIABLE property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the autoedit2OrAUTOEDITOrVARIABLE property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getAUTOEDIT2OrAUTOEDITOrVARIABLE().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link JAXBElement }{@code <}{@link SetVarData }{@code >}
	 * {@link JAXBElement }{@code <}{@link SetVarDataOld }{@code >}
	 * {@link JAXBElement }{@code <}{@link SetVarData }{@code >}
	 *
	 *
	 */
	public List<JAXBElement<?>> getAUTOEDIT2OrAUTOEDITOrVARIABLE() {
		if (autoedit2OrAUTOEDITOrVARIABLE == null) {
			autoedit2OrAUTOEDITOrVARIABLE = new ArrayList<>();
		}
		return this.autoedit2OrAUTOEDITOrVARIABLE;
	}

	/**
	 * Gets the value of the tablename property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTABLENAME() {
		return tablename;
	}

	/**
	 * Sets the value of the tablename property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTABLENAME(String value) {
		this.tablename = value;
	}

	/**
	 * Gets the value of the name property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getNAME() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setNAME(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the dsn property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDSN() {
		return dsn;
	}

	/**
	 * Sets the value of the dsn property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDSN(String value) {
		this.dsn = value;
	}

	/**
	 * Gets the value of the odate property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getODATE() {
		return odate;
	}

	/**
	 * Sets the value of the odate property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setODATE(String value) {
		this.odate = value;
	}

	/**
	 * Gets the value of the remote property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getREMOTE() {
		return remote;
	}

	/**
	 * Sets the value of the remote property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setREMOTE(String value) {
		this.remote = value;
	}

	/**
	 * Gets the value of the datacenter property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDATACENTER() {
		return datacenter;
	}

	/**
	 * Sets the value of the datacenter property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDATACENTER(String value) {
		this.datacenter = value;
	}

}
