//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.09 at 11:04:38 AM EST
//

package com.bluehouseinc.dataconverter.parsers.bmc.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import lombok.ToString;

/**
 * <p>
 * Java class for DoIfRerunData complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DoIfRerunData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="CONFIRM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FPGMS" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FPROCS" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TPGMS" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TPROCS" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@ToString
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DoIfRerunData")
public class DoIfRerunData {

	@XmlAttribute(name = "CONFIRM")
	protected String confirm;
	@XmlAttribute(name = "FPGMS")
	protected String fpgms;
	@XmlAttribute(name = "FPROCS")
	protected String fprocs;
	@XmlAttribute(name = "TPGMS")
	protected String tpgms;
	@XmlAttribute(name = "TPROCS")
	protected String tprocs;

	/**
	 * Gets the value of the confirm property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCONFIRM() {
		return confirm;
	}

	/**
	 * Sets the value of the confirm property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCONFIRM(String value) {
		this.confirm = value;
	}

	/**
	 * Gets the value of the fpgms property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getFPGMS() {
		return fpgms;
	}

	/**
	 * Sets the value of the fpgms property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setFPGMS(String value) {
		this.fpgms = value;
	}

	/**
	 * Gets the value of the fprocs property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getFPROCS() {
		return fprocs;
	}

	/**
	 * Sets the value of the fprocs property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setFPROCS(String value) {
		this.fprocs = value;
	}

	/**
	 * Gets the value of the tpgms property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTPGMS() {
		return tpgms;
	}

	/**
	 * Sets the value of the tpgms property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTPGMS(String value) {
		this.tpgms = value;
	}

	/**
	 * Gets the value of the tprocs property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTPROCS() {
		return tprocs;
	}

	/**
	 * Sets the value of the tprocs property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTPROCS(String value) {
		this.tprocs = value;
	}

}
