//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.09 at 11:04:38 AM EST
//

package com.bluehouseinc.dataconverter.parsers.bmc.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import lombok.ToString;

/**
 * <p>
 * Java class for DoRemedyData complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DoRemedyData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="URGENCY" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SUMMARY" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@ToString
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DoRemedyData")
public class DoRemedyData {

	@XmlAttribute(name = "URGENCY")
	protected String urgency;
	@XmlAttribute(name = "DESCRIPTION")
	protected String description;
	@XmlAttribute(name = "SUMMARY")
	protected String summary;

	/**
	 * Gets the value of the urgency property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getURGENCY() {
		return urgency;
	}

	/**
	 * Sets the value of the urgency property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setURGENCY(String value) {
		this.urgency = value;
	}

	/**
	 * Gets the value of the description property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDESCRIPTION() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDESCRIPTION(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the summary property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getSUMMARY() {
		return summary;
	}

	/**
	 * Sets the value of the summary property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setSUMMARY(String value) {
		this.summary = value;
	}

}
