//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.09 at 11:04:38 AM EST
//

package com.bluehouseinc.dataconverter.parsers.bmc.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import lombok.ToString;

/**
 * <p>
 * Java class for DoSysoutData complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DoSysoutData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="OPTION" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PAR" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FROM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@ToString
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DoSysoutData")
public class DoSysoutData {

	@XmlAttribute(name = "OPTION")
	protected String option;
	@XmlAttribute(name = "PAR")
	protected String par;
	@XmlAttribute(name = "FROM")
	protected String from;

	/**
	 * Gets the value of the option property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getOPTION() {
		return option;
	}

	/**
	 * Sets the value of the option property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setOPTION(String value) {
		this.option = value;
	}

	/**
	 * Gets the value of the par property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getPAR() {
		return par;
	}

	/**
	 * Sets the value of the par property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setPAR(String value) {
		this.par = value;
	}

	/**
	 * Gets the value of the from property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getFROM() {
		return from;
	}

	/**
	 * Sets the value of the from property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setFROM(String value) {
		this.from = value;
	}

}
