//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.09 at 11:04:38 AM EST
//

package com.bluehouseinc.dataconverter.parsers.bmc.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

import lombok.ToString;

/**
 * <p>
 * Java class for OnData complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="OnData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;choice&gt;
 *           &lt;element name="DO" type="{}DoActionData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="DO_TABLE" type="{}DoActionData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="DO_GROUP" type="{}DoActionData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="DOACTION" type="{}DoActionData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="ACTION" type="{}DoActionData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="DOCOND" type="{}DoCondData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="DOCTBRULE" type="{}DoCtbRuleData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="DOFORCEJOB" type="{}DoForceJobData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="DOIFRERUN" type="{}DoIfRerunData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="DOMAIL" type="{}DoMailData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="DOREMEDY" type="{}DoRemedyData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="DOAUTOEDIT2" type="{}SetVarData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="DOAUTOEDIT" type="{}SetVarDataOld" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="DOVARIABLE" type="{}SetVarData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="DOSHOUT" type="{}DoShoutData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="DOOUTPUT" type="{}DoSysoutData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="DOSYSOUT" type="{}DoSysoutData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="STMT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PGMS" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PROCS" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CODE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AND_OR" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PATTERN" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FROM_COLUMN" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TO_COLUMN" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@ToString
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OnData", propOrder = { "doOrDOTABLEOrDOGROUP" })
public class OnData {

	@XmlElementRefs({ @XmlElementRef(name = "DO", type = JAXBElement.class, required = false), @XmlElementRef(name = "DO_TABLE", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "DO_GROUP", type = JAXBElement.class, required = false), @XmlElementRef(name = "DOACTION", type = JAXBElement.class, required = false), @XmlElementRef(name = "ACTION", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "DOCOND", type = JAXBElement.class, required = false), @XmlElementRef(name = "DOCTBRULE", type = JAXBElement.class, required = false), @XmlElementRef(name = "DOFORCEJOB", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "DOIFRERUN", type = JAXBElement.class, required = false), @XmlElementRef(name = "DOMAIL", type = JAXBElement.class, required = false), @XmlElementRef(name = "DOREMEDY", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "DOAUTOEDIT2", type = JAXBElement.class, required = false), @XmlElementRef(name = "DOAUTOEDIT", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "DOVARIABLE", type = JAXBElement.class, required = false), @XmlElementRef(name = "DOSHOUT", type = JAXBElement.class, required = false), @XmlElementRef(name = "DOOUTPUT", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "DOSYSOUT", type = JAXBElement.class, required = false) })
	protected List<JAXBElement<?>> doOrDOTABLEOrDOGROUP;
	@XmlAttribute(name = "STMT")
	protected String stmt;
	@XmlAttribute(name = "PGMS")
	protected String pgms;
	@XmlAttribute(name = "PROCS")
	protected String procs;
	@XmlAttribute(name = "CODE")
	protected String code;
	@XmlAttribute(name = "AND_OR")
	protected String andor;
	@XmlAttribute(name = "PATTERN")
	protected String pattern;
	@XmlAttribute(name = "FROM_COLUMN")
	protected String fromcolumn;
	@XmlAttribute(name = "TO_COLUMN")
	protected String tocolumn;

	/**
	 * Gets the value of the doOrDOTABLEOrDOGROUP property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the doOrDOTABLEOrDOGROUP property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getDOOrDOTABLEOrDOGROUP().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link JAXBElement }{@code <}{@link DoActionData }{@code >}
	 * {@link JAXBElement }{@code <}{@link DoActionData }{@code >}
	 * {@link JAXBElement }{@code <}{@link DoActionData }{@code >}
	 * {@link JAXBElement }{@code <}{@link DoActionData }{@code >}
	 * {@link JAXBElement }{@code <}{@link DoActionData }{@code >}
	 * {@link JAXBElement }{@code <}{@link DoCondData }{@code >}
	 * {@link JAXBElement }{@code <}{@link DoCtbRuleData }{@code >}
	 * {@link JAXBElement }{@code <}{@link DoForceJobData }{@code >}
	 * {@link JAXBElement }{@code <}{@link DoIfRerunData }{@code >}
	 * {@link JAXBElement }{@code <}{@link DoMailData }{@code >}
	 * {@link JAXBElement }{@code <}{@link DoRemedyData }{@code >}
	 * {@link JAXBElement }{@code <}{@link SetVarData }{@code >}
	 * {@link JAXBElement }{@code <}{@link SetVarDataOld }{@code >}
	 * {@link JAXBElement }{@code <}{@link DoSetVarData }{@code >}
	 * {@link JAXBElement }{@code <}{@link DoShoutData }{@code >}
	 * {@link JAXBElement }{@code <}{@link DoSysoutData }{@code >}
	 * {@link JAXBElement }{@code <}{@link DoSysoutData }{@code >}
	 *
	 *
	 */
	public List<JAXBElement<?>> getDOOrDOTABLEOrDOGROUP() {
		if (doOrDOTABLEOrDOGROUP == null) {
			doOrDOTABLEOrDOGROUP = new ArrayList<>();
		}
		return this.doOrDOTABLEOrDOGROUP;
	}

	/**
	 * Gets the value of the stmt property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getSTMT() {
		return stmt;
	}

	/**
	 * Sets the value of the stmt property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setSTMT(String value) {
		this.stmt = value;
	}

	/**
	 * Gets the value of the pgms property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getPGMS() {
		return pgms;
	}

	/**
	 * Sets the value of the pgms property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setPGMS(String value) {
		this.pgms = value;
	}

	/**
	 * Gets the value of the procs property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getPROCS() {
		return procs;
	}

	/**
	 * Sets the value of the procs property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setPROCS(String value) {
		this.procs = value;
	}

	/**
	 * Gets the value of the code property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCODE() {
		return code;
	}

	/**
	 * Sets the value of the code property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCODE(String value) {
		this.code = value;
	}

	/**
	 * Gets the value of the andor property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getANDOR() {
		return andor;
	}

	/**
	 * Sets the value of the andor property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setANDOR(String value) {
		this.andor = value;
	}

	/**
	 * Gets the value of the pattern property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getPATTERN() {
		return pattern;
	}

	/**
	 * Sets the value of the pattern property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setPATTERN(String value) {
		this.pattern = value;
	}

	/**
	 * Gets the value of the fromcolumn property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getFROMCOLUMN() {
		return fromcolumn;
	}

	/**
	 * Sets the value of the fromcolumn property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setFROMCOLUMN(String value) {
		this.fromcolumn = value;
	}

	/**
	 * Gets the value of the tocolumn property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTOCOLUMN() {
		return tocolumn;
	}

	/**
	 * Sets the value of the tocolumn property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTOCOLUMN(String value) {
		this.tocolumn = value;
	}

}
