//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.09 at 11:04:38 AM EST
//

package com.bluehouseinc.dataconverter.parsers.bmc.xml.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

import lombok.ToString;

/**
 * <p>
 * Java class for SimpleFolder complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SimpleFolder"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;choice&gt;
 *           &lt;element name="JOB" type="{}JobData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="ADDITIONAL_FOLDER_DETAILS" type="{}FolderClientData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="DATACENTER" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="VERSION" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PLATFORM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FOLDER_NAME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TABLE_NAME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FOLDER_DSN" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TABLE_DSN" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MODIFIED" type="{}emBoolean" /&gt;
 *       &lt;attribute name="LAST_UPLOAD" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FOLDER_ORDER_METHOD" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TABLE_USERDAILY" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="REAL_FOLDER_ID" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="REAL_TABLEID" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="TYPE" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="USED_BY" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="USED_BY_CODE" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="ENFORCE_VALIDATION"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="N"/&gt;
 *             &lt;enumeration value="Y"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="SITE_STANDARD_NAME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@ToString
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleFolder", propOrder = { "jobOrADDITIONALFOLDERDETAILS" })
public class SimpleFolder {

	@XmlElementRefs({ @XmlElementRef(name = "JOB", type = JAXBElement.class, required = false), @XmlElementRef(name = "ADDITIONAL_FOLDER_DETAILS", type = JAXBElement.class, required = false) })

	// @XmlElements({
	// @XmlElement(name = "JOB", type = JobData.class),
	// @XmlElement(name = "ADDITIONAL_FOLDER_DETAILS", type = FolderClientData.class)
	// })
	protected List<JAXBElement<?>> jobOrADDITIONALFOLDERDETAILS;
	@XmlAttribute(name = "DATACENTER")
	protected String datacenter;
	@XmlAttribute(name = "VERSION")
	protected String version;
	@XmlAttribute(name = "PLATFORM")
	protected String platform;
	@XmlAttribute(name = "FOLDER_NAME")
	protected String foldername;
	@XmlAttribute(name = "TABLE_NAME")
	protected String tablename;
	@XmlAttribute(name = "FOLDER_DSN")
	protected String folderdsn;
	@XmlAttribute(name = "TABLE_DSN")
	protected String tabledsn;
	@XmlAttribute(name = "MODIFIED")
	protected String modified;
	@XmlAttribute(name = "LAST_UPLOAD")
	protected String lastupload;
	@XmlAttribute(name = "FOLDER_ORDER_METHOD")
	protected String folderordermethod;
	@XmlAttribute(name = "TABLE_USERDAILY")
	protected String tableuserdaily;
	@XmlAttribute(name = "REAL_FOLDER_ID")
	protected Integer realfolderid;
	@XmlAttribute(name = "REAL_TABLEID")
	protected Integer realtableid;
	@XmlAttribute(name = "TYPE")
	protected Integer type;
	@XmlAttribute(name = "USED_BY")
	protected String usedby;
	@XmlAttribute(name = "USED_BY_CODE")
	protected Integer usedbycode;
	@XmlAttribute(name = "ENFORCE_VALIDATION")
	protected String enforcevalidation;
	@XmlAttribute(name = "SITE_STANDARD_NAME")
	protected String sitestandardname;

	/**
	 * Gets the value of the jobOrADDITIONALFOLDERDETAILS property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the jobOrADDITIONALFOLDERDETAILS property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getJOBOrADDITIONALFOLDERDETAILS().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link JobData }
	 * {@link FolderClientData }
	 *
	 *
	 */
	public List<JAXBElement<?>> getJOBOrADDITIONALFOLDERDETAILS() {
		if (jobOrADDITIONALFOLDERDETAILS == null) {
			jobOrADDITIONALFOLDERDETAILS = new ArrayList<>();
		}
		return this.jobOrADDITIONALFOLDERDETAILS;
	}

	/**
	 * Gets the value of the datacenter property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDATACENTER() {
		return datacenter;
	}

	/**
	 * Sets the value of the datacenter property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDATACENTER(String value) {
		this.datacenter = value;
	}

	/**
	 * Gets the value of the version property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getVERSION() {
		return version;
	}

	/**
	 * Sets the value of the version property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setVERSION(String value) {
		this.version = value;
	}

	/**
	 * Gets the value of the platform property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getPLATFORM() {
		return platform;
	}

	/**
	 * Sets the value of the platform property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setPLATFORM(String value) {
		this.platform = value;
	}

	/**
	 * Gets the value of the foldername property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getFOLDERNAME() {
		return foldername;
	}

	/**
	 * Sets the value of the foldername property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setFOLDERNAME(String value) {
		this.foldername = value;
	}

	/**
	 * Gets the value of the tablename property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTABLENAME() {
		return tablename;
	}

	/**
	 * Sets the value of the tablename property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTABLENAME(String value) {
		this.tablename = value;
	}

	/**
	 * Gets the value of the folderdsn property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getFOLDERDSN() {
		return folderdsn;
	}

	/**
	 * Sets the value of the folderdsn property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setFOLDERDSN(String value) {
		this.folderdsn = value;
	}

	/**
	 * Gets the value of the tabledsn property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTABLEDSN() {
		return tabledsn;
	}

	/**
	 * Sets the value of the tabledsn property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTABLEDSN(String value) {
		this.tabledsn = value;
	}

	/**
	 * Gets the value of the modified property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getMODIFIED() {
		return modified;
	}

	/**
	 * Sets the value of the modified property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setMODIFIED(String value) {
		this.modified = value;
	}

	/**
	 * Gets the value of the lastupload property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getLASTUPLOAD() {
		return lastupload;
	}

	/**
	 * Sets the value of the lastupload property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setLASTUPLOAD(String value) {
		this.lastupload = value;
	}

	/**
	 * Gets the value of the folderordermethod property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getFOLDERORDERMETHOD() {
		return folderordermethod;
	}

	/**
	 * Sets the value of the folderordermethod property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setFOLDERORDERMETHOD(String value) {
		this.folderordermethod = value;
	}

	/**
	 * Gets the value of the tableuserdaily property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTABLEUSERDAILY() {
		return tableuserdaily;
	}

	/**
	 * Sets the value of the tableuserdaily property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTABLEUSERDAILY(String value) {
		this.tableuserdaily = value;
	}

	/**
	 * Gets the value of the realfolderid property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getREALFOLDERID() {
		return realfolderid;
	}

	/**
	 * Sets the value of the realfolderid property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setREALFOLDERID(Integer value) {
		this.realfolderid = value;
	}

	/**
	 * Gets the value of the realtableid property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getREALTABLEID() {
		return realtableid;
	}

	/**
	 * Sets the value of the realtableid property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setREALTABLEID(Integer value) {
		this.realtableid = value;
	}

	/**
	 * Gets the value of the type property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getTYPE() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setTYPE(Integer value) {
		this.type = value;
	}

	/**
	 * Gets the value of the usedby property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getUSEDBY() {
		return usedby;
	}

	/**
	 * Sets the value of the usedby property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setUSEDBY(String value) {
		this.usedby = value;
	}

	/**
	 * Gets the value of the usedbycode property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getUSEDBYCODE() {
		return usedbycode;
	}

	/**
	 * Sets the value of the usedbycode property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setUSEDBYCODE(Integer value) {
		this.usedbycode = value;
	}

	/**
	 * Gets the value of the enforcevalidation property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getENFORCEVALIDATION() {
		return enforcevalidation;
	}

	/**
	 * Sets the value of the enforcevalidation property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setENFORCEVALIDATION(String value) {
		this.enforcevalidation = value;
	}

	/**
	 * Gets the value of the sitestandardname property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getSITESTANDARDNAME() {
		return sitestandardname;
	}

	/**
	 * Sets the value of the sitestandardname property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setSITESTANDARDNAME(String value) {
		this.sitestandardname = value;
	}

	@Override
	public int hashCode() {
		return Objects.hash(foldername);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if ((obj == null) || (getClass() != obj.getClass()))
			return false;
		SimpleFolder other = (SimpleFolder) obj;
		return Objects.equals(foldername, other.foldername);
	}

	public void setJOBOrADDITIONALFOLDERDETAILS(List<JAXBElement<?>> el) {
		this.jobOrADDITIONALFOLDERDETAILS = el;
	}
}
