//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.09 at 11:04:38 AM EST
//

package com.bluehouseinc.dataconverter.parsers.bmc.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

import lombok.ToString;

/**
 * <p>
 * Java class for SmartFolder complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SmartFolder"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;choice&gt;
 *           &lt;element name="SUB_FOLDER" type="{}SubFolder" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="JOB" type="{}JobData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="ADDITIONAL_FOLDER_DETAILS" type="{}FolderClientData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="AUTOEDIT2" type="{}SetVarData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="AUTOEDIT" type="{}SetVarDataOld" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="VARIABLE" type="{}SetVarData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="SHOUT" type="{}ShoutData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="CONTROL" type="{}ControlResourceData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="INCOND" type="{}InConditionData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="QUANTITATIVE" type="{}QuantitativeResourceData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="OUTCOND" type="{}OutConditionData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="STEP_RANGE" type="{}StepRangeData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="RULE_BASED_CALENDAR" type="{}TagData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="TAG" type="{}TagData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="RULE_BASED_CALENDARS" type="{}JobTagData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="TAG_NAMES" type="{}JobTagData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="ON" type="{}OnData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="ON_TABLE" type="{}OnData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="ON_GROUP" type="{}OnData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="CAPTURE" type="{}CaptureData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="DATACENTER" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="VERSION" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PLATFORM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FOLDER_NAME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TABLE_NAME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FOLDER_DSN" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TABLE_DSN" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MODIFIED" type="{}emBoolean" /&gt;
 *       &lt;attribute name="LAST_UPLOAD" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FOLDER_ORDER_METHOD" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TABLE_USERDAILY" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="REAL_FOLDER_ID" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="REAL_TABLEID" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="TYPE" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="USED_BY" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="USED_BY_CODE" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="ENFORCE_VALIDATION"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="N"/&gt;
 *             &lt;enumeration value="Y"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="SITE_STANDARD_NAME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="JOBISN" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="APPLICATION" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SUB_APPLICATION" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="GROUP" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MEMNAME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="JOBNAME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CREATED_BY" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AUTHOR" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="RUN_AS" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="OWNER" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PRIORITY" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CRITICAL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TASKTYPE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CYCLIC" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NODEID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DOCLIB" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DOCMEM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="INTERVAL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="OVERRIDE_PATH" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="OVERLIB" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MEMLIB" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CMDLINE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CONFIRM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DAYSCAL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="WEEKSCAL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CONFCAL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="RETRO" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MAXWAIT" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="MAXRERUN" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="AUTOARCH" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MAXDAYS" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="MAXRUNS" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="TIMEFROM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TIMETO" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DAYS" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="WEEKDAYS" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="JAN" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FEB" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MAR" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="APR" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MAY" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="JUN" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="JUL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AUG" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SEP" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="OCT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NOV" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DEC" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DATE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="RERUNMEM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DAYS_AND_OR" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CATEGORY" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SHIFT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SHIFTNUM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PDSNAME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MINIMUM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PREVENTNCT2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="OPTION" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FROM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PAR" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SYSDB" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DUE_OUT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="RETEN_DAYS" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="RETEN_GEN" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TASK_CLASS" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PREV_DAY" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ADJUST_COND" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="JOBS_IN_GROUP" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="LARGE_SIZE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IND_CYCLIC" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CREATION_USER" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CREATION_DATE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CREATION_TIME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CHANGE_USERID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CHANGE_DATE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CHANGE_TIME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="JOB_VERSION" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="RULE_BASED_CALENDAR_RELATIONSHIP" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TAG_RELATIONSHIP" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TIMEZONE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="APPL_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="APPL_VER" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="APPL_FORM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CM_VER" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MULTY_AGENT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ACTIVE_FROM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ACTIVE_TILL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SCHEDULING_ENVIRONMENT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SYSTEM_AFFINITY" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="REQUEST_NJE_NODE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="STAT_CAL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="INSTREAM_JCL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="USE_INSTREAM_JCL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DUE_OUT_DAYSOFFSET" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FROM_DAYSOFFSET" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TO_DAYSOFFSET" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="VERSION_OPCODE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="IS_CURRENT_VERSION" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="VERSION_SERIAL" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="VERSION_HOST" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CYCLIC_INTERVAL_SEQUENCE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CYCLIC_TIMES_SEQUENCE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CYCLIC_TOLERANCE" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="CYCLIC_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PARENT_FOLDER" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PARENT_TABLE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="REMOVEATONCE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DAYSKEEPINNOTOK" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="ODATE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FPROCS" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TPGMS" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TPROCS" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@ToString
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SmartFolder", propOrder = { "subfolderOrJOBOrADDITIONALFOLDERDETAILS" })
public class SmartFolder {

	@XmlElementRefs({ @XmlElementRef(name = "SUB_FOLDER", type = JAXBElement.class, required = false), @XmlElementRef(name = "JOB", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "ADDITIONAL_FOLDER_DETAILS", type = JAXBElement.class, required = false), @XmlElementRef(name = "AUTOEDIT2", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "AUTOEDIT", type = JAXBElement.class, required = false), @XmlElementRef(name = "VARIABLE", type = JAXBElement.class, required = false), @XmlElementRef(name = "SHOUT", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "CONTROL", type = JAXBElement.class, required = false), @XmlElementRef(name = "INCOND", type = JAXBElement.class, required = false), @XmlElementRef(name = "QUANTITATIVE", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "OUTCOND", type = JAXBElement.class, required = false), @XmlElementRef(name = "STEP_RANGE", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "RULE_BASED_CALENDAR", type = JAXBElement.class, required = false), @XmlElementRef(name = "TAG", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "RULE_BASED_CALENDARS", type = JAXBElement.class, required = false), @XmlElementRef(name = "TAG_NAMES", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "ON", type = JAXBElement.class, required = false), @XmlElementRef(name = "ON_TABLE", type = JAXBElement.class, required = false), @XmlElementRef(name = "ON_GROUP", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "CAPTURE", type = JAXBElement.class, required = false) })
	protected List<JAXBElement<?>> subfolderOrJOBOrADDITIONALFOLDERDETAILS;
	@XmlAttribute(name = "DATACENTER")
	protected String datacenter;
	@XmlAttribute(name = "VERSION")
	protected String version;
	@XmlAttribute(name = "PLATFORM")
	protected String platform;
	@XmlAttribute(name = "FOLDER_NAME")
	protected String foldername;
	@XmlAttribute(name = "TABLE_NAME")
	protected String tablename;
	@XmlAttribute(name = "FOLDER_DSN")
	protected String folderdsn;
	@XmlAttribute(name = "TABLE_DSN")
	protected String tabledsn;
	@XmlAttribute(name = "MODIFIED")
	protected String modified;
	@XmlAttribute(name = "LAST_UPLOAD")
	protected String lastupload;
	@XmlAttribute(name = "FOLDER_ORDER_METHOD")
	protected String folderordermethod;
	@XmlAttribute(name = "TABLE_USERDAILY")
	protected String tableuserdaily;
	@XmlAttribute(name = "REAL_FOLDER_ID")
	protected Integer realfolderid;
	@XmlAttribute(name = "REAL_TABLEID")
	protected Integer realtableid;
	@XmlAttribute(name = "TYPE")
	protected Integer type;
	@XmlAttribute(name = "USED_BY")
	protected String usedby;
	@XmlAttribute(name = "USED_BY_CODE")
	protected Integer usedbycode;
	@XmlAttribute(name = "ENFORCE_VALIDATION")
	protected String enforcevalidation;
	@XmlAttribute(name = "SITE_STANDARD_NAME")
	protected String sitestandardname;
	@XmlAttribute(name = "JOBISN")
	protected Integer jobisn;
	@XmlAttribute(name = "APPLICATION")
	protected String application;
	@XmlAttribute(name = "SUB_APPLICATION")
	protected String subapplication;
	@XmlAttribute(name = "GROUP")
	protected String group;
	@XmlAttribute(name = "MEMNAME")
	protected String memname;
	@XmlAttribute(name = "JOBNAME")
	protected String jobname;
	@XmlAttribute(name = "DESCRIPTION")
	protected String description;
	@XmlAttribute(name = "CREATED_BY")
	protected String createdby;
	@XmlAttribute(name = "AUTHOR")
	protected String author;
	@XmlAttribute(name = "RUN_AS")
	protected String runas;
	@XmlAttribute(name = "OWNER")
	protected String owner;
	@XmlAttribute(name = "PRIORITY")
	protected String priority;
	@XmlAttribute(name = "CRITICAL")
	protected String critical;
	@XmlAttribute(name = "TASKTYPE")
	protected String tasktype;
	@XmlAttribute(name = "CYCLIC")
	protected String cyclic;
	@XmlAttribute(name = "NODEID")
	protected String nodeid;
	@XmlAttribute(name = "DOCLIB")
	protected String doclib;
	@XmlAttribute(name = "DOCMEM")
	protected String docmem;
	@XmlAttribute(name = "INTERVAL")
	protected String interval;
	@XmlAttribute(name = "OVERRIDE_PATH")
	protected String overridepath;
	@XmlAttribute(name = "OVERLIB")
	protected String overlib;
	@XmlAttribute(name = "MEMLIB")
	protected String memlib;
	@XmlAttribute(name = "CMDLINE")
	protected String cmdline;
	@XmlAttribute(name = "CONFIRM")
	protected String confirm;
	@XmlAttribute(name = "DAYSCAL")
	protected String dayscal;
	@XmlAttribute(name = "WEEKSCAL")
	protected String weekscal;
	@XmlAttribute(name = "CONFCAL")
	protected String confcal;
	@XmlAttribute(name = "RETRO")
	protected String retro;
	@XmlAttribute(name = "MAXWAIT")
	protected Integer maxwait;
	@XmlAttribute(name = "MAXRERUN")
	protected Integer maxrerun;
	@XmlAttribute(name = "AUTOARCH")
	protected String autoarch;
	@XmlAttribute(name = "MAXDAYS")
	protected Integer maxdays;
	@XmlAttribute(name = "MAXRUNS")
	protected Integer maxruns;
	@XmlAttribute(name = "TIMEFROM")
	protected String timefrom;
	@XmlAttribute(name = "TIMETO")
	protected String timeto;
	@XmlAttribute(name = "DAYS")
	protected String days;
	@XmlAttribute(name = "WEEKDAYS")
	protected String weekdays;
	@XmlAttribute(name = "JAN")
	protected String jan;
	@XmlAttribute(name = "FEB")
	protected String feb;
	@XmlAttribute(name = "MAR")
	protected String mar;
	@XmlAttribute(name = "APR")
	protected String apr;
	@XmlAttribute(name = "MAY")
	protected String may;
	@XmlAttribute(name = "JUN")
	protected String jun;
	@XmlAttribute(name = "JUL")
	protected String jul;
	@XmlAttribute(name = "AUG")
	protected String aug;
	@XmlAttribute(name = "SEP")
	protected String sep;
	@XmlAttribute(name = "OCT")
	protected String oct;
	@XmlAttribute(name = "NOV")
	protected String nov;
	@XmlAttribute(name = "DEC")
	protected String dec;
	@XmlAttribute(name = "DATE")
	protected String date;
	@XmlAttribute(name = "RERUNMEM")
	protected String rerunmem;
	@XmlAttribute(name = "DAYS_AND_OR")
	protected String daysandor;
	@XmlAttribute(name = "CATEGORY")
	protected String category;
	@XmlAttribute(name = "SHIFT")
	protected String shift;
	@XmlAttribute(name = "SHIFTNUM")
	protected String shiftnum;
	@XmlAttribute(name = "PDSNAME")
	protected String pdsname;
	@XmlAttribute(name = "MINIMUM")
	protected String minimum;
	@XmlAttribute(name = "PREVENTNCT2")
	protected String preventnct2;
	@XmlAttribute(name = "OPTION")
	protected String option;
	@XmlAttribute(name = "FROM")
	protected String from;
	@XmlAttribute(name = "PAR")
	protected String par;
	@XmlAttribute(name = "SYSDB")
	protected String sysdb;
	@XmlAttribute(name = "DUE_OUT")
	protected String dueout;
	@XmlAttribute(name = "RETEN_DAYS")
	protected String retendays;
	@XmlAttribute(name = "RETEN_GEN")
	protected String retengen;
	@XmlAttribute(name = "TASK_CLASS")
	protected String taskclass;
	@XmlAttribute(name = "PREV_DAY")
	protected String prevday;
	@XmlAttribute(name = "ADJUST_COND")
	protected String adjustcond;
	@XmlAttribute(name = "JOBS_IN_GROUP")
	protected String jobsingroup;
	@XmlAttribute(name = "LARGE_SIZE")
	protected String largesize;
	@XmlAttribute(name = "IND_CYCLIC")
	protected String indcyclic;
	@XmlAttribute(name = "CREATION_USER")
	protected String creationuser;
	@XmlAttribute(name = "CREATION_DATE")
	protected String creationdate;
	@XmlAttribute(name = "CREATION_TIME")
	protected String creationtime;
	@XmlAttribute(name = "CHANGE_USERID")
	protected String changeuserid;
	@XmlAttribute(name = "CHANGE_DATE")
	protected String changedate;
	@XmlAttribute(name = "CHANGE_TIME")
	protected String changetime;
	@XmlAttribute(name = "JOB_VERSION")
	protected String jobversion;
	@XmlAttribute(name = "RULE_BASED_CALENDAR_RELATIONSHIP")
	protected String rulebasedcalendarrelationship;
	@XmlAttribute(name = "TAG_RELATIONSHIP")
	protected String tagrelationship;
	@XmlAttribute(name = "TIMEZONE")
	protected String timezone;
	@XmlAttribute(name = "APPL_TYPE")
	protected String appltype;
	@XmlAttribute(name = "APPL_VER")
	protected String applver;
	@XmlAttribute(name = "APPL_FORM")
	protected String applform;
	@XmlAttribute(name = "CM_VER")
	protected String cmver;
	@XmlAttribute(name = "MULTY_AGENT")
	protected String multyagent;
	@XmlAttribute(name = "ACTIVE_FROM")
	protected String activefrom;
	@XmlAttribute(name = "ACTIVE_TILL")
	protected String activetill;
	@XmlAttribute(name = "SCHEDULING_ENVIRONMENT")
	protected String schedulingenvironment;
	@XmlAttribute(name = "SYSTEM_AFFINITY")
	protected String systemaffinity;
	@XmlAttribute(name = "REQUEST_NJE_NODE")
	protected String requestnjenode;
	@XmlAttribute(name = "STAT_CAL")
	protected String statcal;
	@XmlAttribute(name = "INSTREAM_JCL")
	protected String instreamjcl;
	@XmlAttribute(name = "USE_INSTREAM_JCL")
	protected String useinstreamjcl;
	@XmlAttribute(name = "DUE_OUT_DAYSOFFSET")
	protected String dueoutdaysoffset;
	@XmlAttribute(name = "FROM_DAYSOFFSET")
	protected String fromdaysoffset;
	@XmlAttribute(name = "TO_DAYSOFFSET")
	protected String todaysoffset;
	@XmlAttribute(name = "VERSION_OPCODE")
	protected String versionopcode;
	@XmlAttribute(name = "IS_CURRENT_VERSION")
	protected String iscurrentversion;
	@XmlAttribute(name = "VERSION_SERIAL")
	protected Integer versionserial;
	@XmlAttribute(name = "VERSION_HOST")
	protected String versionhost;
	@XmlAttribute(name = "CYCLIC_INTERVAL_SEQUENCE")
	protected String cyclicintervalsequence;
	@XmlAttribute(name = "CYCLIC_TIMES_SEQUENCE")
	protected String cyclictimessequence;
	@XmlAttribute(name = "CYCLIC_TOLERANCE")
	protected Integer cyclictolerance;
	@XmlAttribute(name = "CYCLIC_TYPE")
	protected String cyclictype;
	@XmlAttribute(name = "PARENT_FOLDER")
	protected String parentfolder;
	@XmlAttribute(name = "PARENT_TABLE")
	protected String parenttable;
	@XmlAttribute(name = "REMOVEATONCE")
	protected String removeatonce;
	@XmlAttribute(name = "DAYSKEEPINNOTOK")
	protected Integer dayskeepinnotok;
	@XmlAttribute(name = "ODATE")
	protected String odate;
	@XmlAttribute(name = "FPROCS")
	protected String fprocs;
	@XmlAttribute(name = "TPGMS")
	protected String tpgms;
	@XmlAttribute(name = "TPROCS")
	protected String tprocs;

	/**
	 * Gets the value of the subfolderOrJOBOrADDITIONALFOLDERDETAILS property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the subfolderOrJOBOrADDITIONALFOLDERDETAILS property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getSUBFOLDEROrJOBOrADDITIONALFOLDERDETAILS().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link JAXBElement }{@code <}{@link SubFolder }{@code >}
	 * {@link JAXBElement }{@code <}{@link JobData }{@code >}
	 * {@link JAXBElement }{@code <}{@link FolderClientData }{@code >}
	 * {@link JAXBElement }{@code <}{@link SetVarData }{@code >}
	 * {@link JAXBElement }{@code <}{@link SetVarDataOld }{@code >}
	 * {@link JAXBElement }{@code <}{@link SetVarData }{@code >}
	 * {@link JAXBElement }{@code <}{@link ShoutData }{@code >}
	 * {@link JAXBElement }{@code <}{@link ControlResourceData }{@code >}
	 * {@link JAXBElement }{@code <}{@link InConditionData }{@code >}
	 * {@link JAXBElement }{@code <}{@link QuantitativeResourceData }{@code >}
	 * {@link JAXBElement }{@code <}{@link OutConditionData }{@code >}
	 * {@link JAXBElement }{@code <}{@link StepRangeData }{@code >}
	 * {@link JAXBElement }{@code <}{@link TagData }{@code >}
	 * {@link JAXBElement }{@code <}{@link TagData }{@code >}
	 * {@link JAXBElement }{@code <}{@link JobTagData }{@code >}
	 * {@link JAXBElement }{@code <}{@link JobTagData }{@code >}
	 * {@link JAXBElement }{@code <}{@link OnData }{@code >}
	 * {@link JAXBElement }{@code <}{@link OnData }{@code >}
	 * {@link JAXBElement }{@code <}{@link OnData }{@code >}
	 * {@link JAXBElement }{@code <}{@link CaptureData }{@code >}
	 *
	 *
	 */
	public List<JAXBElement<?>> getSUBFOLDEROrJOBOrADDITIONALFOLDERDETAILS() {
		if (subfolderOrJOBOrADDITIONALFOLDERDETAILS == null) {
			subfolderOrJOBOrADDITIONALFOLDERDETAILS = new ArrayList<>();
		}
		return this.subfolderOrJOBOrADDITIONALFOLDERDETAILS;
	}

	/**
	 * Gets the value of the datacenter property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDATACENTER() {
		return datacenter;
	}

	/**
	 * Sets the value of the datacenter property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDATACENTER(String value) {
		this.datacenter = value;
	}

	/**
	 * Gets the value of the version property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getVERSION() {
		return version;
	}

	/**
	 * Sets the value of the version property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setVERSION(String value) {
		this.version = value;
	}

	/**
	 * Gets the value of the platform property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getPLATFORM() {
		return platform;
	}

	/**
	 * Sets the value of the platform property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setPLATFORM(String value) {
		this.platform = value;
	}

	/**
	 * Gets the value of the foldername property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getFOLDERNAME() {
		return foldername;
	}

	/**
	 * Sets the value of the foldername property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setFOLDERNAME(String value) {
		this.foldername = value;
	}

	/**
	 * Gets the value of the tablename property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTABLENAME() {
		return tablename;
	}

	/**
	 * Sets the value of the tablename property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTABLENAME(String value) {
		this.tablename = value;
	}

	/**
	 * Gets the value of the folderdsn property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getFOLDERDSN() {
		return folderdsn;
	}

	/**
	 * Sets the value of the folderdsn property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setFOLDERDSN(String value) {
		this.folderdsn = value;
	}

	/**
	 * Gets the value of the tabledsn property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTABLEDSN() {
		return tabledsn;
	}

	/**
	 * Sets the value of the tabledsn property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTABLEDSN(String value) {
		this.tabledsn = value;
	}

	/**
	 * Gets the value of the modified property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getMODIFIED() {
		return modified;
	}

	/**
	 * Sets the value of the modified property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setMODIFIED(String value) {
		this.modified = value;
	}

	/**
	 * Gets the value of the lastupload property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getLASTUPLOAD() {
		return lastupload;
	}

	/**
	 * Sets the value of the lastupload property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setLASTUPLOAD(String value) {
		this.lastupload = value;
	}

	/**
	 * Gets the value of the folderordermethod property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getFOLDERORDERMETHOD() {
		return folderordermethod;
	}

	/**
	 * Sets the value of the folderordermethod property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setFOLDERORDERMETHOD(String value) {
		this.folderordermethod = value;
	}

	/**
	 * Gets the value of the tableuserdaily property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTABLEUSERDAILY() {
		return tableuserdaily;
	}

	/**
	 * Sets the value of the tableuserdaily property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTABLEUSERDAILY(String value) {
		this.tableuserdaily = value;
	}

	/**
	 * Gets the value of the realfolderid property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getREALFOLDERID() {
		return realfolderid;
	}

	/**
	 * Sets the value of the realfolderid property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setREALFOLDERID(Integer value) {
		this.realfolderid = value;
	}

	/**
	 * Gets the value of the realtableid property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getREALTABLEID() {
		return realtableid;
	}

	/**
	 * Sets the value of the realtableid property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setREALTABLEID(Integer value) {
		this.realtableid = value;
	}

	/**
	 * Gets the value of the type property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getTYPE() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setTYPE(Integer value) {
		this.type = value;
	}

	/**
	 * Gets the value of the usedby property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getUSEDBY() {
		return usedby;
	}

	/**
	 * Sets the value of the usedby property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setUSEDBY(String value) {
		this.usedby = value;
	}

	/**
	 * Gets the value of the usedbycode property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getUSEDBYCODE() {
		return usedbycode;
	}

	/**
	 * Sets the value of the usedbycode property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setUSEDBYCODE(Integer value) {
		this.usedbycode = value;
	}

	/**
	 * Gets the value of the enforcevalidation property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getENFORCEVALIDATION() {
		return enforcevalidation;
	}

	/**
	 * Sets the value of the enforcevalidation property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setENFORCEVALIDATION(String value) {
		this.enforcevalidation = value;
	}

	/**
	 * Gets the value of the sitestandardname property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getSITESTANDARDNAME() {
		return sitestandardname;
	}

	/**
	 * Sets the value of the sitestandardname property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setSITESTANDARDNAME(String value) {
		this.sitestandardname = value;
	}

	/**
	 * Gets the value of the jobisn property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getJOBISN() {
		return jobisn;
	}

	/**
	 * Sets the value of the jobisn property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setJOBISN(Integer value) {
		this.jobisn = value;
	}

	/**
	 * Gets the value of the application property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getAPPLICATION() {
		return application;
	}

	/**
	 * Sets the value of the application property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setAPPLICATION(String value) {
		this.application = value;
	}

	/**
	 * Gets the value of the subapplication property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getSUBAPPLICATION() {
		return subapplication;
	}

	/**
	 * Sets the value of the subapplication property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setSUBAPPLICATION(String value) {
		this.subapplication = value;
	}

	/**
	 * Gets the value of the group property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getGROUP() {
		return group;
	}

	/**
	 * Sets the value of the group property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setGROUP(String value) {
		this.group = value;
	}

	/**
	 * Gets the value of the memname property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getMEMNAME() {
		return memname;
	}

	/**
	 * Sets the value of the memname property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setMEMNAME(String value) {
		this.memname = value;
	}

	/**
	 * Gets the value of the jobname property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getJOBNAME() {
		return jobname;
	}

	/**
	 * Sets the value of the jobname property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setJOBNAME(String value) {
		this.jobname = value;
	}

	/**
	 * Gets the value of the description property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDESCRIPTION() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDESCRIPTION(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the createdby property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCREATEDBY() {
		return createdby;
	}

	/**
	 * Sets the value of the createdby property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCREATEDBY(String value) {
		this.createdby = value;
	}

	/**
	 * Gets the value of the author property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getAUTHOR() {
		return author;
	}

	/**
	 * Sets the value of the author property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setAUTHOR(String value) {
		this.author = value;
	}

	/**
	 * Gets the value of the runas property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getRUNAS() {
		return runas;
	}

	/**
	 * Sets the value of the runas property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setRUNAS(String value) {
		this.runas = value;
	}

	/**
	 * Gets the value of the owner property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getOWNER() {
		return owner;
	}

	/**
	 * Sets the value of the owner property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setOWNER(String value) {
		this.owner = value;
	}

	/**
	 * Gets the value of the priority property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getPRIORITY() {
		return priority;
	}

	/**
	 * Sets the value of the priority property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setPRIORITY(String value) {
		this.priority = value;
	}

	/**
	 * Gets the value of the critical property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCRITICAL() {
		return critical;
	}

	/**
	 * Sets the value of the critical property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCRITICAL(String value) {
		this.critical = value;
	}

	/**
	 * Gets the value of the tasktype property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTASKTYPE() {
		return tasktype;
	}

	/**
	 * Sets the value of the tasktype property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTASKTYPE(String value) {
		this.tasktype = value;
	}

	/**
	 * Gets the value of the cyclic property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCYCLIC() {
		return cyclic;
	}

	/**
	 * Sets the value of the cyclic property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCYCLIC(String value) {
		this.cyclic = value;
	}

	/**
	 * Gets the value of the nodeid property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getNODEID() {
		return nodeid;
	}

	/**
	 * Sets the value of the nodeid property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setNODEID(String value) {
		this.nodeid = value;
	}

	/**
	 * Gets the value of the doclib property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDOCLIB() {
		return doclib;
	}

	/**
	 * Sets the value of the doclib property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDOCLIB(String value) {
		this.doclib = value;
	}

	/**
	 * Gets the value of the docmem property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDOCMEM() {
		return docmem;
	}

	/**
	 * Sets the value of the docmem property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDOCMEM(String value) {
		this.docmem = value;
	}

	/**
	 * Gets the value of the interval property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getINTERVAL() {
		return interval;
	}

	/**
	 * Sets the value of the interval property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setINTERVAL(String value) {
		this.interval = value;
	}

	/**
	 * Gets the value of the overridepath property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getOVERRIDEPATH() {
		return overridepath;
	}

	/**
	 * Sets the value of the overridepath property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setOVERRIDEPATH(String value) {
		this.overridepath = value;
	}

	/**
	 * Gets the value of the overlib property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getOVERLIB() {
		return overlib;
	}

	/**
	 * Sets the value of the overlib property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setOVERLIB(String value) {
		this.overlib = value;
	}

	/**
	 * Gets the value of the memlib property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getMEMLIB() {
		return memlib;
	}

	/**
	 * Sets the value of the memlib property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setMEMLIB(String value) {
		this.memlib = value;
	}

	/**
	 * Gets the value of the cmdline property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCMDLINE() {
		return cmdline;
	}

	/**
	 * Sets the value of the cmdline property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCMDLINE(String value) {
		this.cmdline = value;
	}

	/**
	 * Gets the value of the confirm property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCONFIRM() {
		return confirm;
	}

	/**
	 * Sets the value of the confirm property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCONFIRM(String value) {
		this.confirm = value;
	}

	/**
	 * Gets the value of the dayscal property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDAYSCAL() {
		return dayscal;
	}

	/**
	 * Sets the value of the dayscal property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDAYSCAL(String value) {
		this.dayscal = value;
	}

	/**
	 * Gets the value of the weekscal property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getWEEKSCAL() {
		return weekscal;
	}

	/**
	 * Sets the value of the weekscal property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setWEEKSCAL(String value) {
		this.weekscal = value;
	}

	/**
	 * Gets the value of the confcal property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCONFCAL() {
		return confcal;
	}

	/**
	 * Sets the value of the confcal property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCONFCAL(String value) {
		this.confcal = value;
	}

	/**
	 * Gets the value of the retro property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getRETRO() {
		return retro;
	}

	/**
	 * Sets the value of the retro property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setRETRO(String value) {
		this.retro = value;
	}

	/**
	 * Gets the value of the maxwait property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getMAXWAIT() {
		return maxwait;
	}

	/**
	 * Sets the value of the maxwait property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setMAXWAIT(Integer value) {
		this.maxwait = value;
	}

	/**
	 * Gets the value of the maxrerun property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getMAXRERUN() {
		return maxrerun;
	}

	/**
	 * Sets the value of the maxrerun property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setMAXRERUN(Integer value) {
		this.maxrerun = value;
	}

	/**
	 * Gets the value of the autoarch property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getAUTOARCH() {
		return autoarch;
	}

	/**
	 * Sets the value of the autoarch property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setAUTOARCH(String value) {
		this.autoarch = value;
	}

	/**
	 * Gets the value of the maxdays property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getMAXDAYS() {
		return maxdays;
	}

	/**
	 * Sets the value of the maxdays property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setMAXDAYS(Integer value) {
		this.maxdays = value;
	}

	/**
	 * Gets the value of the maxruns property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getMAXRUNS() {
		return maxruns;
	}

	/**
	 * Sets the value of the maxruns property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setMAXRUNS(Integer value) {
		this.maxruns = value;
	}

	/**
	 * Gets the value of the timefrom property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTIMEFROM() {
		return timefrom;
	}

	/**
	 * Sets the value of the timefrom property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTIMEFROM(String value) {
		this.timefrom = value;
	}

	/**
	 * Gets the value of the timeto property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTIMETO() {
		return timeto;
	}

	/**
	 * Sets the value of the timeto property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTIMETO(String value) {
		this.timeto = value;
	}

	/**
	 * Gets the value of the days property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDAYS() {
		return days;
	}

	/**
	 * Sets the value of the days property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDAYS(String value) {
		this.days = value;
	}

	/**
	 * Gets the value of the weekdays property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getWEEKDAYS() {
		return weekdays;
	}

	/**
	 * Sets the value of the weekdays property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setWEEKDAYS(String value) {
		this.weekdays = value;
	}

	/**
	 * Gets the value of the jan property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getJAN() {
		return jan;
	}

	/**
	 * Sets the value of the jan property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setJAN(String value) {
		this.jan = value;
	}

	/**
	 * Gets the value of the feb property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getFEB() {
		return feb;
	}

	/**
	 * Sets the value of the feb property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setFEB(String value) {
		this.feb = value;
	}

	/**
	 * Gets the value of the mar property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getMAR() {
		return mar;
	}

	/**
	 * Sets the value of the mar property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setMAR(String value) {
		this.mar = value;
	}

	/**
	 * Gets the value of the apr property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getAPR() {
		return apr;
	}

	/**
	 * Sets the value of the apr property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setAPR(String value) {
		this.apr = value;
	}

	/**
	 * Gets the value of the may property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getMAY() {
		return may;
	}

	/**
	 * Sets the value of the may property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setMAY(String value) {
		this.may = value;
	}

	/**
	 * Gets the value of the jun property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getJUN() {
		return jun;
	}

	/**
	 * Sets the value of the jun property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setJUN(String value) {
		this.jun = value;
	}

	/**
	 * Gets the value of the jul property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getJUL() {
		return jul;
	}

	/**
	 * Sets the value of the jul property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setJUL(String value) {
		this.jul = value;
	}

	/**
	 * Gets the value of the aug property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getAUG() {
		return aug;
	}

	/**
	 * Sets the value of the aug property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setAUG(String value) {
		this.aug = value;
	}

	/**
	 * Gets the value of the sep property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getSEP() {
		return sep;
	}

	/**
	 * Sets the value of the sep property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setSEP(String value) {
		this.sep = value;
	}

	/**
	 * Gets the value of the oct property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getOCT() {
		return oct;
	}

	/**
	 * Sets the value of the oct property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setOCT(String value) {
		this.oct = value;
	}

	/**
	 * Gets the value of the nov property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getNOV() {
		return nov;
	}

	/**
	 * Sets the value of the nov property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setNOV(String value) {
		this.nov = value;
	}

	/**
	 * Gets the value of the dec property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDEC() {
		return dec;
	}

	/**
	 * Sets the value of the dec property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDEC(String value) {
		this.dec = value;
	}

	/**
	 * Gets the value of the date property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDATE() {
		return date;
	}

	/**
	 * Sets the value of the date property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDATE(String value) {
		this.date = value;
	}

	/**
	 * Gets the value of the rerunmem property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getRERUNMEM() {
		return rerunmem;
	}

	/**
	 * Sets the value of the rerunmem property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setRERUNMEM(String value) {
		this.rerunmem = value;
	}

	/**
	 * Gets the value of the daysandor property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDAYSANDOR() {
		return daysandor;
	}

	/**
	 * Sets the value of the daysandor property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDAYSANDOR(String value) {
		this.daysandor = value;
	}

	/**
	 * Gets the value of the category property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCATEGORY() {
		return category;
	}

	/**
	 * Sets the value of the category property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCATEGORY(String value) {
		this.category = value;
	}

	/**
	 * Gets the value of the shift property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getSHIFT() {
		return shift;
	}

	/**
	 * Sets the value of the shift property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setSHIFT(String value) {
		this.shift = value;
	}

	/**
	 * Gets the value of the shiftnum property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getSHIFTNUM() {
		return shiftnum;
	}

	/**
	 * Sets the value of the shiftnum property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setSHIFTNUM(String value) {
		this.shiftnum = value;
	}

	/**
	 * Gets the value of the pdsname property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getPDSNAME() {
		return pdsname;
	}

	/**
	 * Sets the value of the pdsname property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setPDSNAME(String value) {
		this.pdsname = value;
	}

	/**
	 * Gets the value of the minimum property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getMINIMUM() {
		return minimum;
	}

	/**
	 * Sets the value of the minimum property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setMINIMUM(String value) {
		this.minimum = value;
	}

	/**
	 * Gets the value of the preventnct2 property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getPREVENTNCT2() {
		return preventnct2;
	}

	/**
	 * Sets the value of the preventnct2 property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setPREVENTNCT2(String value) {
		this.preventnct2 = value;
	}

	/**
	 * Gets the value of the option property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getOPTION() {
		return option;
	}

	/**
	 * Sets the value of the option property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setOPTION(String value) {
		this.option = value;
	}

	/**
	 * Gets the value of the from property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getFROM() {
		return from;
	}

	/**
	 * Sets the value of the from property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setFROM(String value) {
		this.from = value;
	}

	/**
	 * Gets the value of the par property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getPAR() {
		return par;
	}

	/**
	 * Sets the value of the par property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setPAR(String value) {
		this.par = value;
	}

	/**
	 * Gets the value of the sysdb property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getSYSDB() {
		return sysdb;
	}

	/**
	 * Sets the value of the sysdb property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setSYSDB(String value) {
		this.sysdb = value;
	}

	/**
	 * Gets the value of the dueout property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDUEOUT() {
		return dueout;
	}

	/**
	 * Sets the value of the dueout property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDUEOUT(String value) {
		this.dueout = value;
	}

	/**
	 * Gets the value of the retendays property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getRETENDAYS() {
		return retendays;
	}

	/**
	 * Sets the value of the retendays property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setRETENDAYS(String value) {
		this.retendays = value;
	}

	/**
	 * Gets the value of the retengen property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getRETENGEN() {
		return retengen;
	}

	/**
	 * Sets the value of the retengen property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setRETENGEN(String value) {
		this.retengen = value;
	}

	/**
	 * Gets the value of the taskclass property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTASKCLASS() {
		return taskclass;
	}

	/**
	 * Sets the value of the taskclass property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTASKCLASS(String value) {
		this.taskclass = value;
	}

	/**
	 * Gets the value of the prevday property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getPREVDAY() {
		return prevday;
	}

	/**
	 * Sets the value of the prevday property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setPREVDAY(String value) {
		this.prevday = value;
	}

	/**
	 * Gets the value of the adjustcond property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getADJUSTCOND() {
		return adjustcond;
	}

	/**
	 * Sets the value of the adjustcond property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setADJUSTCOND(String value) {
		this.adjustcond = value;
	}

	/**
	 * Gets the value of the jobsingroup property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getJOBSINGROUP() {
		return jobsingroup;
	}

	/**
	 * Sets the value of the jobsingroup property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setJOBSINGROUP(String value) {
		this.jobsingroup = value;
	}

	/**
	 * Gets the value of the largesize property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getLARGESIZE() {
		return largesize;
	}

	/**
	 * Sets the value of the largesize property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setLARGESIZE(String value) {
		this.largesize = value;
	}

	/**
	 * Gets the value of the indcyclic property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getINDCYCLIC() {
		return indcyclic;
	}

	/**
	 * Sets the value of the indcyclic property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setINDCYCLIC(String value) {
		this.indcyclic = value;
	}

	/**
	 * Gets the value of the creationuser property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCREATIONUSER() {
		return creationuser;
	}

	/**
	 * Sets the value of the creationuser property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCREATIONUSER(String value) {
		this.creationuser = value;
	}

	/**
	 * Gets the value of the creationdate property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCREATIONDATE() {
		return creationdate;
	}

	/**
	 * Sets the value of the creationdate property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCREATIONDATE(String value) {
		this.creationdate = value;
	}

	/**
	 * Gets the value of the creationtime property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCREATIONTIME() {
		return creationtime;
	}

	/**
	 * Sets the value of the creationtime property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCREATIONTIME(String value) {
		this.creationtime = value;
	}

	/**
	 * Gets the value of the changeuserid property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCHANGEUSERID() {
		return changeuserid;
	}

	/**
	 * Sets the value of the changeuserid property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCHANGEUSERID(String value) {
		this.changeuserid = value;
	}

	/**
	 * Gets the value of the changedate property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCHANGEDATE() {
		return changedate;
	}

	/**
	 * Sets the value of the changedate property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCHANGEDATE(String value) {
		this.changedate = value;
	}

	/**
	 * Gets the value of the changetime property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCHANGETIME() {
		return changetime;
	}

	/**
	 * Sets the value of the changetime property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCHANGETIME(String value) {
		this.changetime = value;
	}

	/**
	 * Gets the value of the jobversion property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getJOBVERSION() {
		return jobversion;
	}

	/**
	 * Sets the value of the jobversion property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setJOBVERSION(String value) {
		this.jobversion = value;
	}

	/**
	 * Gets the value of the rulebasedcalendarrelationship property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getRULEBASEDCALENDARRELATIONSHIP() {
		return rulebasedcalendarrelationship;
	}

	/**
	 * Sets the value of the rulebasedcalendarrelationship property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setRULEBASEDCALENDARRELATIONSHIP(String value) {
		this.rulebasedcalendarrelationship = value;
	}

	/**
	 * Gets the value of the tagrelationship property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTAGRELATIONSHIP() {
		return tagrelationship;
	}

	/**
	 * Sets the value of the tagrelationship property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTAGRELATIONSHIP(String value) {
		this.tagrelationship = value;
	}

	/**
	 * Gets the value of the timezone property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTIMEZONE() {
		return timezone;
	}

	/**
	 * Sets the value of the timezone property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTIMEZONE(String value) {
		this.timezone = value;
	}

	/**
	 * Gets the value of the appltype property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getAPPLTYPE() {
		return appltype;
	}

	/**
	 * Sets the value of the appltype property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setAPPLTYPE(String value) {
		this.appltype = value;
	}

	/**
	 * Gets the value of the applver property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getAPPLVER() {
		return applver;
	}

	/**
	 * Sets the value of the applver property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setAPPLVER(String value) {
		this.applver = value;
	}

	/**
	 * Gets the value of the applform property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getAPPLFORM() {
		return applform;
	}

	/**
	 * Sets the value of the applform property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setAPPLFORM(String value) {
		this.applform = value;
	}

	/**
	 * Gets the value of the cmver property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCMVER() {
		return cmver;
	}

	/**
	 * Sets the value of the cmver property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCMVER(String value) {
		this.cmver = value;
	}

	/**
	 * Gets the value of the multyagent property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getMULTYAGENT() {
		return multyagent;
	}

	/**
	 * Sets the value of the multyagent property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setMULTYAGENT(String value) {
		this.multyagent = value;
	}

	/**
	 * Gets the value of the activefrom property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getACTIVEFROM() {
		return activefrom;
	}

	/**
	 * Sets the value of the activefrom property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setACTIVEFROM(String value) {
		this.activefrom = value;
	}

	/**
	 * Gets the value of the activetill property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getACTIVETILL() {
		return activetill;
	}

	/**
	 * Sets the value of the activetill property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setACTIVETILL(String value) {
		this.activetill = value;
	}

	/**
	 * Gets the value of the schedulingenvironment property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getSCHEDULINGENVIRONMENT() {
		return schedulingenvironment;
	}

	/**
	 * Sets the value of the schedulingenvironment property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setSCHEDULINGENVIRONMENT(String value) {
		this.schedulingenvironment = value;
	}

	/**
	 * Gets the value of the systemaffinity property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getSYSTEMAFFINITY() {
		return systemaffinity;
	}

	/**
	 * Sets the value of the systemaffinity property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setSYSTEMAFFINITY(String value) {
		this.systemaffinity = value;
	}

	/**
	 * Gets the value of the requestnjenode property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getREQUESTNJENODE() {
		return requestnjenode;
	}

	/**
	 * Sets the value of the requestnjenode property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setREQUESTNJENODE(String value) {
		this.requestnjenode = value;
	}

	/**
	 * Gets the value of the statcal property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getSTATCAL() {
		return statcal;
	}

	/**
	 * Sets the value of the statcal property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setSTATCAL(String value) {
		this.statcal = value;
	}

	/**
	 * Gets the value of the instreamjcl property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getINSTREAMJCL() {
		return instreamjcl;
	}

	/**
	 * Sets the value of the instreamjcl property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setINSTREAMJCL(String value) {
		this.instreamjcl = value;
	}

	/**
	 * Gets the value of the useinstreamjcl property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getUSEINSTREAMJCL() {
		return useinstreamjcl;
	}

	/**
	 * Sets the value of the useinstreamjcl property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setUSEINSTREAMJCL(String value) {
		this.useinstreamjcl = value;
	}

	/**
	 * Gets the value of the dueoutdaysoffset property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDUEOUTDAYSOFFSET() {
		return dueoutdaysoffset;
	}

	/**
	 * Sets the value of the dueoutdaysoffset property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDUEOUTDAYSOFFSET(String value) {
		this.dueoutdaysoffset = value;
	}

	/**
	 * Gets the value of the fromdaysoffset property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getFROMDAYSOFFSET() {
		return fromdaysoffset;
	}

	/**
	 * Sets the value of the fromdaysoffset property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setFROMDAYSOFFSET(String value) {
		this.fromdaysoffset = value;
	}

	/**
	 * Gets the value of the todaysoffset property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTODAYSOFFSET() {
		return todaysoffset;
	}

	/**
	 * Sets the value of the todaysoffset property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTODAYSOFFSET(String value) {
		this.todaysoffset = value;
	}

	/**
	 * Gets the value of the versionopcode property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getVERSIONOPCODE() {
		return versionopcode;
	}

	/**
	 * Sets the value of the versionopcode property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setVERSIONOPCODE(String value) {
		this.versionopcode = value;
	}

	/**
	 * Gets the value of the iscurrentversion property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getISCURRENTVERSION() {
		return iscurrentversion;
	}

	/**
	 * Sets the value of the iscurrentversion property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setISCURRENTVERSION(String value) {
		this.iscurrentversion = value;
	}

	/**
	 * Gets the value of the versionserial property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getVERSIONSERIAL() {
		return versionserial;
	}

	/**
	 * Sets the value of the versionserial property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setVERSIONSERIAL(Integer value) {
		this.versionserial = value;
	}

	/**
	 * Gets the value of the versionhost property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getVERSIONHOST() {
		return versionhost;
	}

	/**
	 * Sets the value of the versionhost property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setVERSIONHOST(String value) {
		this.versionhost = value;
	}

	/**
	 * Gets the value of the cyclicintervalsequence property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCYCLICINTERVALSEQUENCE() {
		return cyclicintervalsequence;
	}

	/**
	 * Sets the value of the cyclicintervalsequence property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCYCLICINTERVALSEQUENCE(String value) {
		this.cyclicintervalsequence = value;
	}

	/**
	 * Gets the value of the cyclictimessequence property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCYCLICTIMESSEQUENCE() {
		return cyclictimessequence;
	}

	/**
	 * Sets the value of the cyclictimessequence property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCYCLICTIMESSEQUENCE(String value) {
		this.cyclictimessequence = value;
	}

	/**
	 * Gets the value of the cyclictolerance property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getCYCLICTOLERANCE() {
		return cyclictolerance;
	}

	/**
	 * Sets the value of the cyclictolerance property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setCYCLICTOLERANCE(Integer value) {
		this.cyclictolerance = value;
	}

	/**
	 * Gets the value of the cyclictype property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCYCLICTYPE() {
		return cyclictype;
	}

	/**
	 * Sets the value of the cyclictype property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCYCLICTYPE(String value) {
		this.cyclictype = value;
	}

	/**
	 * Gets the value of the parentfolder property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getPARENTFOLDER() {
		return parentfolder;
	}

	/**
	 * Sets the value of the parentfolder property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setPARENTFOLDER(String value) {
		this.parentfolder = value;
	}

	/**
	 * Gets the value of the parenttable property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getPARENTTABLE() {
		return parenttable;
	}

	/**
	 * Sets the value of the parenttable property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setPARENTTABLE(String value) {
		this.parenttable = value;
	}

	/**
	 * Gets the value of the removeatonce property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getREMOVEATONCE() {
		return removeatonce;
	}

	/**
	 * Sets the value of the removeatonce property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setREMOVEATONCE(String value) {
		this.removeatonce = value;
	}

	/**
	 * Gets the value of the dayskeepinnotok property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getDAYSKEEPINNOTOK() {
		return dayskeepinnotok;
	}

	/**
	 * Sets the value of the dayskeepinnotok property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setDAYSKEEPINNOTOK(Integer value) {
		this.dayskeepinnotok = value;
	}

	/**
	 * Gets the value of the odate property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getODATE() {
		return odate;
	}

	/**
	 * Sets the value of the odate property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setODATE(String value) {
		this.odate = value;
	}

	/**
	 * Gets the value of the fprocs property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getFPROCS() {
		return fprocs;
	}

	/**
	 * Sets the value of the fprocs property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setFPROCS(String value) {
		this.fprocs = value;
	}

	/**
	 * Gets the value of the tpgms property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTPGMS() {
		return tpgms;
	}

	/**
	 * Sets the value of the tpgms property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTPGMS(String value) {
		this.tpgms = value;
	}

	/**
	 * Gets the value of the tprocs property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTPROCS() {
		return tprocs;
	}

	/**
	 * Sets the value of the tprocs property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTPROCS(String value) {
		this.tprocs = value;
	}

	public void setSUBFOLDEROrJOBOrADDITIONALFOLDERDETAILS(List<JAXBElement<?>> el) {
		this.subfolderOrJOBOrADDITIONALFOLDERDETAILS = el;
	}
}
