//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.09 at 11:04:38 AM EST
//

package com.bluehouseinc.dataconverter.parsers.bmc.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import lombok.ToString;

/**
 * <p>
 * Java class for TagData complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TagData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TAG_NAME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MAXWAIT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DAYS_AND_OR" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="JAN" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FEB" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MAR" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="APR" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MAY" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="JUN" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="JUL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AUG" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SEP" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="OCT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NOV" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DEC" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DAYSCAL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="WEEKSCAL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CONFCAL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SHIFT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SHIFTNUM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="RETRO" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DATE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DAYS" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="WEEKDAYS" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ACTIVE_FROM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TAGS_ACTIVE_FROM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ACTIVE_TILL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TAGS_ACTIVE_TILL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="LEVEL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@ToString
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TagData")
public class TagData {

	@XmlAttribute(name = "NAME")
	protected String name;
	@XmlAttribute(name = "TAG_NAME")
	protected String tagname;
	@XmlAttribute(name = "MAXWAIT")
	protected String maxwait;
	@XmlAttribute(name = "DAYS_AND_OR")
	protected String daysandor;
	@XmlAttribute(name = "JAN")
	protected String jan;
	@XmlAttribute(name = "FEB")
	protected String feb;
	@XmlAttribute(name = "MAR")
	protected String mar;
	@XmlAttribute(name = "APR")
	protected String apr;
	@XmlAttribute(name = "MAY")
	protected String may;
	@XmlAttribute(name = "JUN")
	protected String jun;
	@XmlAttribute(name = "JUL")
	protected String jul;
	@XmlAttribute(name = "AUG")
	protected String aug;
	@XmlAttribute(name = "SEP")
	protected String sep;
	@XmlAttribute(name = "OCT")
	protected String oct;
	@XmlAttribute(name = "NOV")
	protected String nov;
	@XmlAttribute(name = "DEC")
	protected String dec;
	@XmlAttribute(name = "DAYSCAL")
	protected String dayscal;
	@XmlAttribute(name = "WEEKSCAL")
	protected String weekscal;
	@XmlAttribute(name = "CONFCAL")
	protected String confcal;
	@XmlAttribute(name = "SHIFT")
	protected String shift;
	@XmlAttribute(name = "SHIFTNUM")
	protected String shiftnum;
	@XmlAttribute(name = "RETRO")
	protected String retro;
	@XmlAttribute(name = "DATE")
	protected String date;
	@XmlAttribute(name = "DAYS")
	protected String days;
	@XmlAttribute(name = "WEEKDAYS")
	protected String weekdays;
	@XmlAttribute(name = "ACTIVE_FROM")
	protected String activefrom;
	@XmlAttribute(name = "TAGS_ACTIVE_FROM")
	protected String tagsactivefrom;
	@XmlAttribute(name = "ACTIVE_TILL")
	protected String activetill;
	@XmlAttribute(name = "TAGS_ACTIVE_TILL")
	protected String tagsactivetill;
	@XmlAttribute(name = "LEVEL")
	protected String level;

	/**
	 * Gets the value of the name property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getNAME() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setNAME(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the tagname property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTAGNAME() {
		return tagname;
	}

	/**
	 * Sets the value of the tagname property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTAGNAME(String value) {
		this.tagname = value;
	}

	/**
	 * Gets the value of the maxwait property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getMAXWAIT() {
		return maxwait;
	}

	/**
	 * Sets the value of the maxwait property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setMAXWAIT(String value) {
		this.maxwait = value;
	}

	/**
	 * Gets the value of the daysandor property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDAYSANDOR() {
		return daysandor;
	}

	/**
	 * Sets the value of the daysandor property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDAYSANDOR(String value) {
		this.daysandor = value;
	}

	/**
	 * Gets the value of the jan property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getJAN() {
		return jan;
	}

	/**
	 * Sets the value of the jan property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setJAN(String value) {
		this.jan = value;
	}

	/**
	 * Gets the value of the feb property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getFEB() {
		return feb;
	}

	/**
	 * Sets the value of the feb property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setFEB(String value) {
		this.feb = value;
	}

	/**
	 * Gets the value of the mar property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getMAR() {
		return mar;
	}

	/**
	 * Sets the value of the mar property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setMAR(String value) {
		this.mar = value;
	}

	/**
	 * Gets the value of the apr property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getAPR() {
		return apr;
	}

	/**
	 * Sets the value of the apr property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setAPR(String value) {
		this.apr = value;
	}

	/**
	 * Gets the value of the may property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getMAY() {
		return may;
	}

	/**
	 * Sets the value of the may property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setMAY(String value) {
		this.may = value;
	}

	/**
	 * Gets the value of the jun property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getJUN() {
		return jun;
	}

	/**
	 * Sets the value of the jun property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setJUN(String value) {
		this.jun = value;
	}

	/**
	 * Gets the value of the jul property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getJUL() {
		return jul;
	}

	/**
	 * Sets the value of the jul property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setJUL(String value) {
		this.jul = value;
	}

	/**
	 * Gets the value of the aug property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getAUG() {
		return aug;
	}

	/**
	 * Sets the value of the aug property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setAUG(String value) {
		this.aug = value;
	}

	/**
	 * Gets the value of the sep property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getSEP() {
		return sep;
	}

	/**
	 * Sets the value of the sep property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setSEP(String value) {
		this.sep = value;
	}

	/**
	 * Gets the value of the oct property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getOCT() {
		return oct;
	}

	/**
	 * Sets the value of the oct property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setOCT(String value) {
		this.oct = value;
	}

	/**
	 * Gets the value of the nov property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getNOV() {
		return nov;
	}

	/**
	 * Sets the value of the nov property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setNOV(String value) {
		this.nov = value;
	}

	/**
	 * Gets the value of the dec property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDEC() {
		return dec;
	}

	/**
	 * Sets the value of the dec property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDEC(String value) {
		this.dec = value;
	}

	/**
	 * Gets the value of the dayscal property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDAYSCAL() {
		return dayscal;
	}

	/**
	 * Sets the value of the dayscal property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDAYSCAL(String value) {
		this.dayscal = value;
	}

	/**
	 * Gets the value of the weekscal property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getWEEKSCAL() {
		return weekscal;
	}

	/**
	 * Sets the value of the weekscal property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setWEEKSCAL(String value) {
		this.weekscal = value;
	}

	/**
	 * Gets the value of the confcal property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCONFCAL() {
		return confcal;
	}

	/**
	 * Sets the value of the confcal property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCONFCAL(String value) {
		this.confcal = value;
	}

	/**
	 * Gets the value of the shift property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getSHIFT() {
		return shift;
	}

	/**
	 * Sets the value of the shift property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setSHIFT(String value) {
		this.shift = value;
	}

	/**
	 * Gets the value of the shiftnum property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getSHIFTNUM() {
		return shiftnum;
	}

	/**
	 * Sets the value of the shiftnum property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setSHIFTNUM(String value) {
		this.shiftnum = value;
	}

	/**
	 * Gets the value of the retro property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getRETRO() {
		return retro;
	}

	/**
	 * Sets the value of the retro property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setRETRO(String value) {
		this.retro = value;
	}

	/**
	 * Gets the value of the date property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDATE() {
		return date;
	}

	/**
	 * Sets the value of the date property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDATE(String value) {
		this.date = value;
	}

	/**
	 * Gets the value of the days property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDAYS() {
		return days;
	}

	/**
	 * Sets the value of the days property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDAYS(String value) {
		this.days = value;
	}

	/**
	 * Gets the value of the weekdays property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getWEEKDAYS() {
		return weekdays;
	}

	/**
	 * Sets the value of the weekdays property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setWEEKDAYS(String value) {
		this.weekdays = value;
	}

	/**
	 * Gets the value of the activefrom property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getACTIVEFROM() {
		return activefrom;
	}

	/**
	 * Sets the value of the activefrom property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setACTIVEFROM(String value) {
		this.activefrom = value;
	}

	/**
	 * Gets the value of the tagsactivefrom property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTAGSACTIVEFROM() {
		return tagsactivefrom;
	}

	/**
	 * Sets the value of the tagsactivefrom property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTAGSACTIVEFROM(String value) {
		this.tagsactivefrom = value;
	}

	/**
	 * Gets the value of the activetill property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getACTIVETILL() {
		return activetill;
	}

	/**
	 * Sets the value of the activetill property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setACTIVETILL(String value) {
		this.activetill = value;
	}

	/**
	 * Gets the value of the tagsactivetill property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTAGSACTIVETILL() {
		return tagsactivetill;
	}

	/**
	 * Sets the value of the tagsactivetill property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTAGSACTIVETILL(String value) {
		this.tagsactivetill = value;
	}

	/**
	 * Gets the value of the level property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getLEVEL() {
		return level;
	}

	/**
	 * Sets the value of the level property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setLEVEL(String value) {
		this.level = value;
	}

}
