//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.09 at 11:04:38 AM EST
//

package com.bluehouseinc.dataconverter.parsers.bmc.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for WCMNotesData complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="WCMNotesData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;choice&gt;
 *           &lt;element name="NOTE_HISTORY" type="{}WCMNote" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="NOTES_STATUS"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="NOTSET"/&gt;
 *             &lt;enumeration value="OPEN"/&gt;
 *             &lt;enumeration value="APPROVED"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="MESSAGE_DRAFT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WCMNotesData", propOrder = { "notehistory" })
public class WCMNotesData {

	@XmlElement(name = "NOTE_HISTORY")
	protected List<WCMNote> notehistory;
	@XmlAttribute(name = "NOTES_STATUS")
	protected String notesstatus;
	@XmlAttribute(name = "MESSAGE_DRAFT")
	protected String messagedraft;

	/**
	 * Gets the value of the notehistory property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the notehistory property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getNOTEHISTORY().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link WCMNote }
	 *
	 *
	 */
	public List<WCMNote> getNOTEHISTORY() {
		if (notehistory == null) {
			notehistory = new ArrayList<>();
		}
		return this.notehistory;
	}

	/**
	 * Gets the value of the notesstatus property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getNOTESSTATUS() {
		return notesstatus;
	}

	/**
	 * Sets the value of the notesstatus property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setNOTESSTATUS(String value) {
		this.notesstatus = value;
	}

	/**
	 * Gets the value of the messagedraft property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getMESSAGEDRAFT() {
		return messagedraft;
	}

	/**
	 * Sets the value of the messagedraft property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setMESSAGEDRAFT(String value) {
		this.messagedraft = value;
	}

}
