//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.09 at 11:04:38 AM EST
//

package com.bluehouseinc.dataconverter.parsers.bmc.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for WorkspaceData complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="WorkspaceData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;choice&gt;
 *           &lt;element name="ADDITIONAL_WORKSPACE_DETAILS" type="{}ClientData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="TYPE"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="UNKNOWN"/&gt;
 *             &lt;enumeration value="REGULAR"/&gt;
 *             &lt;enumeration value="REQUEST"/&gt;
 *             &lt;enumeration value="PROMOTION"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="STATE"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="WSSTATE_UNKNOWN"/&gt;
 *             &lt;enumeration value="WSSTATE_EndUserWorks"/&gt;
 *             &lt;enumeration value="WSSTATE_Submitted"/&gt;
 *             &lt;enumeration value="WSSTATE_SchedulerWorks"/&gt;
 *             &lt;enumeration value="WSSTATE_Rejected"/&gt;
 *             &lt;enumeration value="WSSTATE_Approved"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="OWNER" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CREATED_TIME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="UPDATED_TIME" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CHANGE_TICKET_ID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ASSOCIATED_END_USER" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TRANSFER_SIDE_TIMESTAMP" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="EMAIL_RECIPIENT" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkspaceData", propOrder = { "additionalworkspacedetails" })
public class WorkspaceData {

	@XmlElement(name = "ADDITIONAL_WORKSPACE_DETAILS")
	protected List<ClientData> additionalworkspacedetails;
	@XmlAttribute(name = "ID")
	protected Integer id;
	@XmlAttribute(name = "TYPE")
	protected String type;
	@XmlAttribute(name = "STATE")
	protected String state;
	@XmlAttribute(name = "NAME")
	protected String name;
	@XmlAttribute(name = "DESCRIPTION")
	protected String description;
	@XmlAttribute(name = "OWNER")
	protected String owner;
	@XmlAttribute(name = "CREATED_TIME")
	protected String createdtime;
	@XmlAttribute(name = "UPDATED_TIME")
	protected String updatedtime;
	@XmlAttribute(name = "CHANGE_TICKET_ID")
	protected String changeticketid;
	@XmlAttribute(name = "ASSOCIATED_END_USER")
	protected String associatedenduser;
	@XmlAttribute(name = "TRANSFER_SIDE_TIMESTAMP")
	protected String transfersidetimestamp;
	@XmlAttribute(name = "EMAIL_RECIPIENT")
	protected String emailrecipient;

	/**
	 * Gets the value of the additionalworkspacedetails property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the additionalworkspacedetails property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getADDITIONALWORKSPACEDETAILS().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ClientData }
	 *
	 *
	 */
	public List<ClientData> getADDITIONALWORKSPACEDETAILS() {
		if (additionalworkspacedetails == null) {
			additionalworkspacedetails = new ArrayList<>();
		}
		return this.additionalworkspacedetails;
	}

	/**
	 * Gets the value of the id property.
	 *
	 * @return
	 *         possible object is
	 *         {@link Integer }
	 *
	 */
	public Integer getID() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link Integer }
	 *
	 */
	public void setID(Integer value) {
		this.id = value;
	}

	/**
	 * Gets the value of the type property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTYPE() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTYPE(String value) {
		this.type = value;
	}

	/**
	 * Gets the value of the state property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getSTATE() {
		return state;
	}

	/**
	 * Sets the value of the state property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setSTATE(String value) {
		this.state = value;
	}

	/**
	 * Gets the value of the name property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getNAME() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setNAME(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the description property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getDESCRIPTION() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setDESCRIPTION(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the owner property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getOWNER() {
		return owner;
	}

	/**
	 * Sets the value of the owner property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setOWNER(String value) {
		this.owner = value;
	}

	/**
	 * Gets the value of the createdtime property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCREATEDTIME() {
		return createdtime;
	}

	/**
	 * Sets the value of the createdtime property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCREATEDTIME(String value) {
		this.createdtime = value;
	}

	/**
	 * Gets the value of the updatedtime property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getUPDATEDTIME() {
		return updatedtime;
	}

	/**
	 * Sets the value of the updatedtime property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setUPDATEDTIME(String value) {
		this.updatedtime = value;
	}

	/**
	 * Gets the value of the changeticketid property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getCHANGETICKETID() {
		return changeticketid;
	}

	/**
	 * Sets the value of the changeticketid property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setCHANGETICKETID(String value) {
		this.changeticketid = value;
	}

	/**
	 * Gets the value of the associatedenduser property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getASSOCIATEDENDUSER() {
		return associatedenduser;
	}

	/**
	 * Sets the value of the associatedenduser property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setASSOCIATEDENDUSER(String value) {
		this.associatedenduser = value;
	}

	/**
	 * Gets the value of the transfersidetimestamp property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getTRANSFERSIDETIMESTAMP() {
		return transfersidetimestamp;
	}

	/**
	 * Sets the value of the transfersidetimestamp property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setTRANSFERSIDETIMESTAMP(String value) {
		this.transfersidetimestamp = value;
	}

	/**
	 * Gets the value of the emailrecipient property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getEMAILRECIPIENT() {
		return emailrecipient;
	}

	/**
	 * Sets the value of the emailrecipient property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setEMAILRECIPIENT(String value) {
		this.emailrecipient = value;
	}

}
