#!/bin/bash

filesToAddAfterFormatting=()
containsJavaOrXmlOrMarkdown=0

# Collect all files currently in staging area, and check if there are any Java/XML/Markdown files
for entry in $(git status --porcelain | sed -r 's/[ \t]+/-/g')
do
  # entry can be for example:
  # MM-src/main/java/net/project/MyController.java
  # -M-src/main/java/net/project/AnotherController.java

 if [[ $entry == M* ]] ; then
    filesToAddAfterFormatting+=("${entry:2}") # strips the prefix
 fi

 if [[ $entry == *.java ]] || [[ $entry == *.xml ]] || [[ $entry == *.md ]] ; then
    containsJavaOrXmlOrMarkdown=1
 fi
done;


# If any Java/XML/Markdown files are found, run mvn spotless:apply and mvn spotless:check
if [ "$containsJavaOrXmlOrMarkdown" == "1" ] ; then
  echo "Java and/or XML/Markdown file(s) found in staging, running:  mvn spotless:apply";
  mvn spotless:apply;
  echo "Running mvn spotless:check";
  mvn spotless:check;
else
  echo "Not running spotless:apply";
fi

# Add the files that were in the staging area
for fileToAdd in "${filesToAddAfterFormatting[@]}"
do
  echo "re-adding $fileToAdd after formatting";
  git add "$fileToAdd";
done;